---
title: 'Best Next Study: A Case of Customer Satifaction and Retention'

output:
  distill::distill_article:
    toc: true
    toc_depth: 2
    highlight: pygments
    highlight_downlit: false
---
```{r clear_data , echo=FALSE , warning=FALSE , message = FALSE, results = "hide"}
 rm(list=ls())
```

## Load Required Packages


```{r load_packages , warning=FALSE , message = FALSE, }

  suppressPackageStartupMessages({
    require(devtools)  #to load the package from Github
    require(dplyr)#for better manipulating data

  })
devtools::install_github("bestnextstudy/bestnextstudy")
library(bestnextstudy)
```

## Load Data from `BestNextStudy` Package and Reorder Factor Levels
```{r load_data ,  warning=FALSE , message = FALSE, }
#customer_satisfaction_data is pre-built into the package
data = bestnextstudy::customer_satisfaction_data
###REORDER FACTOR LEVELS
data$Exchange <- factor(data$Exchange, levels = c("Goods", "Services", "Mixed"))
data$Market <- factor(data$Market, levels = c("B2C", "B2B", "Mixed"))
data$Location <- factor(data$Location, levels = c("North America", "Europe", "Asia"))
data$CS_Scale_Items <- factor(data$CS_Scale_Items, levels = c("Single Item", "Multiple Items"))
data$CS_Scale_Points <- factor(data$CS_Scale_Points, levels = c("5", "7", "10"))
```

## Calculating A-Efficiency and D-Efficieny
```{r efficiency_1 , warning=FALSE , message = FALSE, }
variables =  c("Exchange", "Market", "Location", "CS_Scale_Items", "CS_Scale_Points", "Retention_Measure")
labels = c("Exchange", "Market", "Location", "CS_Scale_Items", "CS_Scale_Points", "Retention_Measure")
corrvar = "Corr"
##RUN
eff = bestnextstudy::efficiency(data = data, variables = variables, labels = labels, corrvar = corrvar)
eff
```

## Calculating True Efficiency and Optimal Efficiency over time
```{r efficiency_2 ,  warning=FALSE , message = FALSE, results = "hide"}
naval = "Don't Know"
yrvar = "Year"
# yrs = sort(unique(data$Year))[-c(1:3)]
yrs = c(2005, 2008, 2011, 2014, 2017, 2021)
##RUN
eff_over_time = bestnextstudy::efficiency_over_time(data = data, variables = variables, labels = labels, corrvar = corrvar, naval = naval, yrvar = yrvar, yrs = yrs)
```

### Plotting the true and optimal efficiencis over time
```{r efficiency_2_plot ,  warning=FALSE , message = FALSE}
bestnextstudy::efficiency_over_time_plot(eff_over_time)
# 'eff_over_time' is the output from bestnextstudy::efficiency_over_time
```

## Identifying 10 Next Best Studies

```{r efficiency_Next_Best , warning=FALSE , message = FALSE,results = "hide"}
nstudies_add = 10 #number of next studies

eff_next_best = bestnextstudy::efficiency_next_best_studies(data = data, variables = variables, labels = labels, corrvar = corrvar, naval = naval, nstudies_add = nstudies_add)
```

### 10 Studies Based on A-Efficiency are
```{r efficiency_Next_Best_A,  warning=FALSE , message = FALSE}


eff_next_best_A = as.data.frame(eff_next_best$next_best_studies_A) #best next studies based on a-efficiency
 options(knitr.kable.NA = '')
 
```

```{r efficiency_Next_Best_A_print, echo= FALSE,  warning=FALSE , message = FALSE}
require(kableExtra)
 
eff_next_best_A %>%
  kbl(caption = "10 Studies Based on A-Efficiency") %>%
  kable_classic(full_width = F, html_font = "Cambria") %>%
  kable_styling(bootstrap_options = "striped", full_width = F, position = "center")


```


### 10 Studies Based on D-Efficiency are
```{r efficiency_Next_Best_D, echo=FALSE , warning=FALSE , message = FALSE}
library(dplyr)
library(kableExtra)

eff_next_best_D = as.data.frame(eff_next_best$next_best_studies_D) #best next studies based on a-efficiency
 options(knitr.kable.NA = '')
```

```{r efficiency_Next_Best_D_print, echo= FALSE , warning=FALSE , message = FALSE}
require(kableExtra)
eff_next_best_D %>%
  kbl(caption = "10 Studies Based on D-Efficiency") %>%
  kable_classic(full_width = F, html_font = "Cambria") %>%
  kable_styling(bootstrap_options = "striped", full_width = F, position = "center")


```
